name: ci/cd 

on:
  push:
    branches:
      - main

jobs:
  codecheckout-build:
    uses: ./.github/workflows/docker-b-p.yml
    secrets: inherit 
  
  deployment:
      needs: codecheckout-build 
      uses: ./.github/workflows/deploy.yml
      secrets: inherit
