name: Docker Publish

on:
 workflow_call:
   

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push to Docker Hub the forntend 
        uses: docker/build-push-action@v6
        with:
            context: ./frontend
            file: ./frontend/Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-frontend:${{ github.ref_name }}
              ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-frontend:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-frontend:${{ github.sha }}
      - name: Build & Push to Docker Hub the backend 
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-backend:${{ github.ref_name }}
              ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-backend:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-backend:${{ github.sha }}
      
      - name: Build & Push to Docker Hub the nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-nginx:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-nginx:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bookmyshow-nginx:${{ github.sha }}
